export const dummy_data = [
    {name:"META", weight:3 , value:-0.03},
    {name:"TSLA", weight:4 , value:0.03},
    {name:"ROKU", weight:1 , value:-0.05},
    {name:"AMC", weight:2 , value:0.07},
    {name:"GME", weight:2 , value:0.51},
    {name:"NVDA", weight:2 , value:-0.06},
    {name:"NFLX", weight:3 , value:-0.03},
    {name:"AMZN", weight:4 , value:0.07},
    {name:"AAPL", weight:5 , value:0.05},
    {name:"TSM", weight:1 , value:-0.13},
    {name:"Nio", weight:2 , value:-0.18},
    {name:"Baba", weight:2 , value:-0.1},
    {name:"V", weight:3, value:-0.01},
    {name:"K", weight:5, value:0.05},
    {name:"QQQ", weight:5 , value:0.05},
    {name:"SPG", weight:3 , value:0.03},
]